services:
  8k95pv27i1:
    container_name: 8k95pv27i1_app
    image: ghcr.io/mr-devloper005/marketingsspot.com:latest
    env_file:
      - .env
    network_mode: bridge
    restart: always
    ports:
      - "127.0.0.1:3216:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 5m
      timeout: 3s
      retries: 2
